### ISSUE TITLE
any docker command gives error: bad symbol table

### ISSUE THREAD

**Issue by fmmajd** [docker/cli#2208]
hi

I installed docker successfully on my Ubuntu 18.04 machine, with no errors whatsoever. 

But when I use any docker command at all, even help commands, I get the following error:

```bash
runtime: pcdata is -2 and 76 args stack map entries for net/http.(*Transport).dialConn (targetpc=0x5584a709f7cb)
fatal error: bad symbol table

runtime stack:
runtime.throw(0x5584a832ffb2, 0x10)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.getStackMap(0x7fff5b929f88, 0x7fff5b92a090, 0x5584a709f701, 0x4, 0x7fff5b929c98, 0x80, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/stack.go:1274 +0x522
runtime.adjustframe(0x7fff5b929f88, 0x7fff5b92a078, 0x5584aa251a20)
	/usr/local/go/src/runtime/stack.go:628 +0x86
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000001c80, 0x0, 0x0, 0x7fffffff, 0x5584a9033f50, 0x7fff5b92a078, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:341 +0x13a0
runtime.copystack(0xc000001c80, 0x1000, 0x101)
	/usr/local/go/src/runtime/stack.go:881 +0x25d
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1050 +0x301
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:429 +0x84

goroutine 8 [copystack]:
net/http.(*Transport).dialConn(0xc000497b00, 0x5584a90b8ce0, 0xc000056100, 0x0, 0x5584a831c9af, 0x4, 0xc00045aee0, 0x17, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1150 +0x1fcc fp=0xc000083f00 sp=0xc000083ef8 pc=0x5584a709f7cc
net/http.(*Transport).getConn.func4(0xc000497b00, 0x5584a90b8ce0, 0xc000056100, 0xc000516b10, 0xc0003800c0)
	/usr/local/go/src/net/http/transport.go:1017 +0xa8 fp=0xc000083fb8 sp=0xc000083f00 pc=0x5584a70a97f8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000083fc0 sp=0xc000083fb8 pc=0x5584a6d96b91
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:1016 +0x457

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc000497b00, 0xc000516ae0, 0x0, 0x5584a831c9af, 0x4, 0xc00045aee0, 0x17, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1022 +0x63f
net/http.(*Transport).roundTrip(0xc000497b00, 0xc000518700, 0x10, 0xc000298710, 0xc00024f4d0)
	/usr/local/go/src/net/http/transport.go:531 +0x6f1
net/http.(*Transport).RoundTrip(0xc000497b00, 0xc000518700, 0xc000497b00, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x37
net/http.send(0xc000518700, 0x5584a9063520, 0xc000497b00, 0x0, 0x0, 0x0, 0xc000594608, 0x5584a6f8d788, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x463
net/http.(*Client).send(0xc0005169c0, 0xc000518700, 0x0, 0x0, 0x0, 0xc000594608, 0x0, 0x1, 0x5584a8d39540)
	/usr/local/go/src/net/http/client.go:174 +0xfd
net/http.(*Client).do(0xc0005169c0, 0xc000518700, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x27b
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
github.com/docker/cli/vendor/github.com/docker/docker/client.(*Client).doRequest(0xc00045cd80, 0x5584a90b8ce0, 0xc000056100, 0xc000518600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/vendor/github.com/docker/docker/client/request.go:134 +0x13f
github.com/docker/cli/vendor/github.com/docker/docker/client.(*Client).Ping(0xc00045cd80, 0x5584a90b8ce0, 0xc000056100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/vendor/github.com/docker/docker/client/ping.go:26 +0x167
github.com/docker/cli/cli/command.(*DockerCli).initializeFromClient(0xc00059a000)
	/go/src/github.com/docker/cli/cli/command/cli.go:346 +0x67
github.com/docker/cli/cli/command.(*DockerCli).Initialize(0xc00059a000, 0xc0002280a0, 0x0, 0x0, 0x0, 0x5584a7208bd0, 0xc000518500)
	/go/src/github.com/docker/cli/cli/command/cli.go:255 +0x4a2
github.com/docker/cli/cli.(*TopLevelCommand).Initialize(0xc00029fbc0, 0x0, 0x0, 0x0, 0x5584a9060de0, 0xc000298610)
	/go/src/github.com/docker/cli/cli/cobra.go:155 +0x7a
github.com/docker/cli/cli.(*TopLevelCommand).HandleGlobalFlags(0xc00029fbc0, 0xc00029fbc0, 0x1, 0xc000586270, 0xc00024fef8, 0x5584a76182cc, 0xc000000180)
	/go/src/github.com/docker/cli/cli/cobra.go:143 +0x152
main.runDocker(0xc00059a000, 0x5584a9063820, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:252 +0x58
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

goroutine 34 [syscall]:
os/signal.signal_recv(0x5584a6d96b96)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9e
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x43

goroutine 36 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x5584aa2b7ca0)
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:943 +0x8d
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:403 +0x6e
```

when I get the service status:
```bash
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-11-30 12:22:03 +0330; 2h 56min ago
     Docs: https://docs.docker.com
 Main PID: 22660 (dockerd)
    Tasks: 12
   CGroup: /system.slice/docker.service
           └─22660 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.133892106+03:30" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.133900961+03:30" level=warning msg="Your kernel does not support cgroup blkio weight"
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.133909687+03:30" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.134151192+03:30" level=info msg="Loading containers: start."
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.202981422+03:30" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a 
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.248985871+03:30" level=info msg="Loading containers: done."
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.310411374+03:30" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.310553054+03:30" level=info msg="Daemon has completed initialization"
Nov 30 12:22:03 fatemeh dockerd[22660]: time="2019-11-30T12:22:03.339684607+03:30" level=info msg="API listen on /var/run/docker.sock"
Nov 30 12:22:03 fatemeh systemd[1]: Started Docker Application Container Engine.
```

my machine is:
  Intel® Core™ i3-7100 CPU @ 3.90GHz × 4 
  16G memory
  Ubuntu 18.04 64-bit
  3.28.2
  500G disk

I tried completely uninstalling docker, removing all the files, updating everything on my machine and reinstalling it again. the same thing happened.

I can't tell you the version, cause the version command doesn't work. but it's the latest version in this or last week.

**Comment by fmmajd** [comment]
I unisntalled the docker again, and this time checked the version.

version: 5:19.03.5~3-0~ubuntu-bionic gives me an error.

but if I use version:5:19.03.4~3-0~ubuntu-bionic instead, it works.

probably a bug

**Comment by thaJeztah** [comment]
We've not seen other reports of this, and it looks like this issue happened quite a while back, so I'll close it for now
