### ISSUE TITLE
docker cp bug

### ISSUE THREAD

**Issue by zhangguanzhang** [docker/cli#2219]
info:
```
Server Version: 19.03.4
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
```
```
# echo docker cp temp:/${filename}.mp4 $temp_dir/
docker cp temp:/am8mmGLMvi-Q.mp4 /tmp/tmp.wzKV5W6FSN/
# echo docker cp temp:/${filename}.mp4 .
docker cp temp:/am8mmGLMvi-Q.mp4 .
#  docker cp temp:/${filename}.mp4 .
#  docker cp temp:/${filename}.mp4 $temp_dir/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55565d77c3c8]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ValidateOutputPath(0xc0001f3a00, 0x14, 0xc0001f3a00, 0x14)
	/go/src/github.com/docker/cli/cli/command/utils.go:142 +0x118
github.com/docker/cli/cli/command/container.copyFromContainer(0x55565f217d80, 0xc000056088, 0x55565f25a220, 0xc0004340f0, 0x0, 0x7ffcd14bc859, 0x11, 0x7ffcd14bc86b, 0x14, 0x7ffcd14bc854, ...)
	/go/src/github.com/docker/cli/cli/command/container/cp.go:131 +0xd2
github.com/docker/cli/cli/command/container.runCopy(0x55565f25a220, 0xc0004340f0, 0x7ffcd14bc854, 0x16, 0x7ffcd14bc86b, 0x14, 0x0, 0x0, 0xc000275c58)
	/go/src/github.com/docker/cli/cli/command/container/cp.go:102 +0x3b4
github.com/docker/cli/cli/command/container.NewCopyCommand.func1(0xc0002c7900, 0xc000457900, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/container/cp.go:67 +0xe3
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002c7900, 0xc0004da1f0, 0x2, 0x2, 0xc0002c7900, 0xc0004da1f0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000446f00, 0xc0004da1e0, 0x3, 0x3)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc0004340f0, 0x55565f1c28c0, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d5
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3
```

**Comment by zhangguanzhang** [comment]
```
# ll /tmp/
total 394520
drwxrwxrwx. 2 root root        20 Aug 24 05:38 admin
drwx------  3 root root        17 Nov 24 10:28 systemd-private-bc5f5f36b57f48dfa36cf42474792f4b-chronyd.service-t3kGfV
-rw-------  1 root root         0 Dec  8 09:27 tmp.eAiLt0xlZx
-rw-------  1 root root         0 Dec  8 09:27 tmp.j1HLDlFTTa
-rw-r--r--  1 root root 403988478 Oct 19 08:27 tmp.wzKV5W6FSN
```

**Comment by slava-vishnyakov** [comment]
Multiple people reported similar issues with docker cp: 

https://github.com/dokku/dokku-elasticsearch/issues/75

**Comment by thaJeztah** [comment]
Problem looks to be here; https://github.com/docker/cli/blob/v19.03.5/cli/command/utils.go#L142

Looks like `fileInfo` is `nil` in some cases
