### ISSUE TITLE
SIGSEGV after a reboot on newly installed Debian10

### ISSUE THREAD

**Issue by FrancYescO** [docker/cli#2361]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

docker cli commands should run normally

### Actual behavior
After a **reboot** docker-cli does not work ALL commands (also info or version) response is a SIGSEGV, `apt-get reinstall docker-ce-cli` fix the issue
```
root@frabian:/home/francyesco# docker version
unexpected fault address 0x5598baf9c2ab
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5598baf9c2ab pc=0x5598b8f03f60]

goroutine 1 [running, locked to thread]:
runtime.throw(0x5598ba451b34, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x74 fp=0xc00006c740 sp=0xc00006c710 pc=0x5598b8e93194
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x405 fp=0xc00006c770 sp=0xc00006c740 pc=0x5598b8ea7f35
internal/fmtsort.init()
	<autogenerated>:1 fp=0xc00006c778 sp=0xc00006c770 pc=0x5598b8f03f60
fmt.init()
	<autogenerated>:1 +0x4c fp=0xc00006c788 sp=0xc00006c778 pc=0x5598b8f49a6c
main.init()
	<autogenerated>:1 +0x4a fp=0xc00006c798 sp=0xc00006c788 pc=0x5598ba44b08a
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x1d0 fp=0xc00006c7e0 sp=0xc00006c798 pc=0x5598b8e94af0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x5598b8ec02c1
```

### Steps to reproduce the behavior

1. install Debian 10
2. install docker as per instruction https://docs.docker.com/install/linux/docker-ce/debian/
3. reboot

**Output of `docker version`:**

```
root@frabian:/home/francyesco# docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
root@frabian:/home/francyesco# docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.921GiB
 Name: frabian
 ID: 7LYO:RZ5Z:CVRD:BMC6:MITV:PY5W:QFFB:3LUN:UOAR:GQTI:KKH5:5XKC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**physical enviroment**
```
root@frabian:/home/francyesco# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D510   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1662.602
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3325.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D510   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1662.602
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3325.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by thaJeztah** [comment]
The panic seems to originate somewhere in this part;

https://github.com/docker/cli/blob/v19.03.6/vendor/github.com/modern-go/reflect2/type_map.go#L21-L30

which goes to https://github.com/docker/cli/blob/v19.03.6/vendor/github.com/modern-go/reflect2/type_map.go#L64

And somehow results in a panic at https://github.com/docker/cli/blob/v19.03.6/vendor/github.com/modern-go/reflect2/type_map.go#L79

**Comment by thaJeztah** [comment]
closing as this went stale and the kubernetes dependency has been removed
