### ISSUE TITLE
signal SIGSEGV: segmentation violation during `docker login`

### ISSUE THREAD

**Issue by mandarjog** [docker/cli#3010]
**Description**
I am attempting a docker login after adding a new `credHelpers` like so.
```
 located at [/usr/local/google/home/mjog/.docker/config.json]:
 {
  "credHelpers": {
    "gcr.io": "gcloud",
    "us-west2-docker.pkg.dev": "gcloud",
    "marketplace.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "us.gcr.io": "gcloud"
  }
}
```
I was not locally logged onto `gcloud` so the login failed and resulted in this

```
docker login us-west2-docker.pkg.dev
ERROR: (gcloud.auth.docker-helper) There was a problem refreshing your current auth tokens: ('invalid_grant: Bad Request', u'{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')
Please run:

  $ gcloud auth login

to obtain new credentials.
If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55eb13b45406]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x55eb15587e80, 0xc00035ab60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55eb154f7200, 0xc0005b6bb0, 0xc00059d968)
	/go/src/github.com/docker/cli/cli/command/registry.go:128 +0x46
github.com/docker/cli/cli/command/registry.runLogin(0x55eb15587e80, 0xc00035ab60, 0x7ffd7edf2e69, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x223
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00018f080, 0xc0005b6090, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xcc
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00018f080, 0xc0003526f0, 0x1, 0x1, 0xc00018f080, 0xc0003526f0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000445b80, 0xc0003526e0, 0x2, 0x2)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00035ab60, 0x55eb154f9f80, 0xc0000ec010)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.7.17-1rodete5-amd64
 Operating System: Debian GNU/Linux rodete
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.36GiB
 Name: mjog.c.googlers.com
 ID: FFTI:FZT4:CRSW:GPFZ:LXPM:L3A2:BLOW:SV64:5ZGV:2AVU:ZIBX:5TJP
 Docker Root Dir: /usr/local/google/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 33
  System Time: 2021-03-12T22:54:28.064936545Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false
```

**Comment by tlowerison** [comment]
Hey I just was running into this myself earlier today, I think this [pr](https://github.com/docker/cli/pull/2959) fixed the problem. I updated docker to 20.10.5 and the problem went away, hope that helps for you!

**Comment by thaJeztah** [comment]
looks like this went stale, and possibly fixed per above. closing
