### ISSUE TITLE
"docker stats --no-stream -a" panic at small probability

### ISSUE THREAD

**Issue by ehocchen** [docker/cli#3057]
**Description**

"docker stats --no-stream -a" panic with below info:
```
panic: send on closed channel
goroutine 40 [running]:
github.com/docker/cli/cli/command/container.runStats.func1(0xc4200b0240, 0xc4200b02a0)
#011/go/src/github.com/docker/cli/cli/command/container/stats.go:78 +0x272
created by github.com/docker/cli/cli/command/container.runStats
#011/go/src/github.com/docker/cli/cli/command/container/stats.go:152 +0x1058
```

**Describe the results you received:**
panic: send on closed channel

**Describe the results you expected:**
no panic message print

**Additional information you deem important (e.g. issue happens only occasionally):**

I have about 100 network devices doing: 
"docker stats --no-stream -a" run every 120 second, and execute "docker exec xxx some_cmd" periodically.
It happens three times in 10 days.

It seems the close of channel in the consumer side cause this. 
There's a chance "container events" write to channel between the channel close and process exit.

**Output of `docker version`:**

```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:41:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.9.0-11-2-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.327GiB
Name: LFRZ_A18_406-01-12-49.S0-132-132
ID: G5VL:4VY5:NSJP:A4ER:XX6M:CI3B:RGGZ:G6CS:QNEE:EFZT:POSO:EKRC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by teivah** [comment]
It looks to me as the same issue as https://github.com/docker/cli/issues/3482
