### ISSUE TITLE
-q flag broken by Snyk advertisement

### ISSUE THREAD

**Issue by andrewsw** [docker/cli#3062]
**Description**

The recent addition of the Snyk advertisement to docker cli output breaks the `-q` output. 

While I can appreciate the desire to advertise fancy new things, doing so when the `-q` flag is enabled is a problem and definitely unexpected. The option is clearly intended for exactly the use case detailed below -- inlining a build into some other process that consumes the image id.

**Steps to reproduce the issue:**
1. write a script that inlines the output of a docker build with `-q`. We have automation of the form `docker run -rm <options> $(docker build -q -f Dockerfile-foo .) bash -c "do something here"`
2. run the script
3. observe disaster

**Describe the results you received:**
```
$ docker build --platform linux/amd64 -q -f Dockerfile-translations . 
sha256:1043fa0804f5ab74b1617126cc23e1da4636ef9d0021aedcb86dcf905a08b395

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

With that unexpected output, we get this kind of result in our docker runs:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module '/Use'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

That output isn't particularly interesting except it shows how `Use` from the beginning of the advertisement is polluting the commands.

**Describe the results you expected:**
```
$ docker build --platform linux/amd64 -q -f Dockerfile-translations . 
sha256:1043fa0804f5ab74b1617126cc23e1da4636ef9d0021aedcb86dcf905a08b395
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 12
  Running: 11
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: QE35:3MAS:PJWT:TDXU:EJNI:VDU7:S3FU:6H66:D2XC:6BJ6:QBSO:S5NJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 136
  Goroutines: 118
  System Time: 2021-04-24T00:37:51.304563343Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Mac OS

**Comment by chris-crone** [comment]
Thanks for the report @andrewsw. This is fixed in code and will be released in the next version of Desktop: https://github.com/docker/compose-cli/issues/1517

To work around this, you can use `docker scan` once or use the env var `DOCKER_SCAN_SUGGEST=false`.
