### ISSUE TITLE
Crash on github.com/docker/cli/cli/command/stack/kubernetes/convert.go

### ISSUE THREAD

**Issue by jetm** [docker/cli#4014]
### Description

In a ROCK-Pi deleting a container, randomly a crash happens with the following error message:

```None
panic: regexp: Compile(`([\w\.]*)\W*(==|!=)\W*([\w\.]*)`): error parsing regexp: invalid escape sequence: `\W`

goroutine 1 [running]:
 regexp.MustCompile({0xaaaab44fdc41, 0x1f})
	regexp/regexp.go:311 +0x118
github.com/docker/cli/cli/command/stack/kubernetes.init()
github.com/docker/cli/cli/command/stack/kubernetes/convert.go:448 +0x34
```

### Reproduce

Manually, it's hard to reproduce. Only has been seen once in a CI system. In the CI it runs:
```
docker pull docker.io/library/alpine
docker run -itd docker.io/library/alpine:latest '/bin/sh'
docker container rm --force <CONTAINER_ID>
```  

### Expected behavior

`docker container rm --force <CONTAINER_ID>` should not crash

### docker version

```bash
Client:
 Version:           20.10.17-ce
 API version:       1.41
 Go version:        go1.17.13
 Git commit:        100c70180f
 Built:             Thu Feb  9 00:00:25 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.13
  Git commit:       3949ff121e-unsupported
  Built:            Wed Jun  1 18:45:24 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.6.8-8-g579a6380e.m
  GitCommit:        579a6380ec93ab92a6e7f26167fe4f18dfcf2a4b.m
 runc:
  Version:          1.1.3+dev
  GitCommit:        v1.1.3-2-g1e7bb5b7-dirty
 docker-init:
  Version:          0.19.0
  GitCommit:        b9f42a0-dirty
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 0
 Server Version: 20.10.17-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 579a6380ec93ab92a6e7f26167fe4f18dfcf2a4b.m
 runc version: v1.1.3-2-g1e7bb5b7-dirty
 init version: b9f42a0-dirty
 Kernel Version: 5.15.87-yocto-standard
 Operating System: TRS (Trusted Reference Stack) unstable (kirkstone)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.927GiB
 Name: trs-qemuarm64
 ID: 4RPS:7BHC:U5XT:D5P7:EABE:EE3R:V5Q2:NT2N:YORF:344U:H7FE:EBAI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bsousaa** [comment]
This feature is deprecated and has been removed. Additionally, it seems like its a custom build - you may report it to the Yocto package managers:

>  runc version: v1.1.3-2-g1e7bb5b7-dirty
>  init version: b9f42a0-dirty
>  Kernel Version: 5.15.87-yocto-standard
>  Operating System: TRS (Trusted Reference Stack) unstable (kirkstone)

Please note that it is built from a modified source code (-dirty).
