### ISSUE TITLE
Failed to bind to address https://[::]:443: address already in use

### ISSUE THREAD

**Issue by ilchenkoevgeny** [docker/cli#4167]
### Description

My environment:

**Windows Home Premium 11 version 21H2 build 22000.1696
Microsoft Visual Studio Community 2022 Version 17.5.2
ASP.NET Core 6.0.15
Docker Desktop 4.18.0 (104112)
ASP.NET and Web Tools 17.5.317.37931**

I create an empty ASP project. net core 6.0 with docker support from template. I run it in the docker and get an error:

```
System.IO.IOException: "Failed to bind to address https://[::]:443: address already in use."
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
```

Docker file:

```dockerfile
#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["WebApplication4.csproj", "."]
RUN dotnet restore "./WebApplication4.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebApplication4.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApplication4.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplication4.dll"]
```

launch settengs file:

```json
{
  "profiles": {
    "WebApplication4": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true,
      "applicationUrl": "https://localhost:7123;http://localhost:5163"
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
      "publishAllPorts": true,
      "useSSL": true
    }
  },
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:22907",
      "sslPort": 44357
    }
  }
}
```

At first the application ran several times and I saw that everything worked fine, but then it started to give an error, although I did not change anything in the docker file or in the application itself. 

### Reproduce

1. Create ASP NET. Core 6.0 Web Application via template
2. Run in docker

### docker version

```bash
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:28:08 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:18:42 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.4)
  compose: Docker Compose (Docker Inc., v2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.19)
  init: Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.2)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.9.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.31GiB
 Name: docker-desktop
 ID: KHMZ:ALWJ:A32Y:3Q2X:KQD3:PAOE:PQWD:QCCI:VOIK:BKPI:VZZA:QOTV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

```json
{
  "Id": "6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e",
  "Created": "2023-04-06T10:08:44.363223938Z",
  "Path": "tail",
  "Args": [
    "-f",
    "/dev/null"
  ],
  "State": {
    "Status": "running",
    "Running": true,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "Dead": false,
    "Pid": 24127,
    "ExitCode": 0,
    "Error": "",
    "StartedAt": "2023-04-06T10:08:44.83935766Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
  },
  "Image": "sha256:bbc1c02b99bae1bc014caa806073242557b722c170b0f702ecc774b855ca1453",
  "ResolvConfPath": "/var/lib/docker/containers/6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e/resolv.conf",
  "HostnamePath": "/var/lib/docker/containers/6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e/hostname",
  "HostsPath": "/var/lib/docker/containers/6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e/hosts",
  "LogPath": "/var/lib/docker/containers/6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e/6eeb0ef14e495a3445060aa7451ef8df123c8b12d20a371b1ab771310a222a5e-json.log",
  "Name": "/WebApplication4",
  "RestartCount": 0,
  "Driver": "overlay2",
  "Platform": "linux",
  "MountLabel": "",
  "ProcessLabel": "",
  "AppArmorProfile": "",
  "ExecIDs": [
    "4f428e535a289adfb81f1fedef6b86d0de1efc74957e6ef28fa993b7ffaa28ab"
  ],
  "HostConfig": {
    "Binds": [
      "C:\\Users\\ilche\\vsdbg\\vs2017u5:/remote_debugger:rw",
      "C:\\Users\\ilche\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets:ro",
      "C:\\Users\\ilche\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https:ro",
      "C:\\Users\\ilche\\source\\repos\\WebApplication4:/app",
      "C:\\Users\\ilche\\source\\repos\\WebApplication4:/src/",
      "C:\\Users\\ilche\\.nuget\\packages\\:/root/.nuget/fallbackpackages2",
      "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\NuGetPackages:/root/.nuget/fallbackpackages"
    ],
    "ContainerIDFile": "",
    "LogConfig": {
      "Type": "json-file",
      "Config": {}
    },
    "NetworkMode": "default",
    "PortBindings": {},
    "RestartPolicy": {
      "Name": "no",
      "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": null,
    "CapAdd": null,
    "CapDrop": null,
    "CgroupnsMode": "private",
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": null,
    "GroupAdd": null,
    "IpcMode": "private",
    "Cgroup": "",
    "Links": null,
    "OomScoreAdj": 0,
    "PidMode": "",
    "Privileged": false,
    "PublishAllPorts": true,
    "ReadonlyRootfs": false,
    "SecurityOpt": null,
    "UTSMode": "",
    "UsernsMode": "",
    "ShmSize": 67108864,
    "Runtime": "runc",
    "ConsoleSize": [
      0,
      0
    ],
    "Isolation": "",
    "CpuShares": 0,
    "Memory": 0,
    "NanoCpus": 0,
    "CgroupParent": "",
    "BlkioWeight": 0,
    "BlkioWeightDevice": [],
    "BlkioDeviceReadBps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteIOps": null,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "Devices": [],
    "DeviceCgroupRules": null,
    "DeviceRequests": null,
    "KernelMemory": 0,
    "KernelMemoryTCP": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": null,
    "OomKillDisable": null,
    "PidsLimit": null,
    "Ulimits": null,
    "CpuCount": 0,
    "CpuPercent": 0,
    "IOMaximumIOps": 0,
    "IOMaximumBandwidth": 0,
    "MaskedPaths": [
      "/proc/asound",
      "/proc/acpi",
      "/proc/kcore",
      "/proc/keys",
      "/proc/latency_stats",
      "/proc/timer_list",
      "/proc/timer_stats",
      "/proc/sched_debug",
      "/proc/scsi",
      "/sys/firmware"
    ],
    "ReadonlyPaths": [
      "/proc/bus",
      "/proc/fs",
      "/proc/irq",
      "/proc/sys",
      "/proc/sysrq-trigger"
    ]
  },
  "GraphDriver": {
    "Data": {
      "LowerDir": "/var/lib/docker/overlay2/8b5bf15317a6bf2f1d24a90d9f92be8ab7b0c0ab7d12bf9fc928ec48a8b426bb-init/diff:/var/lib/docker/overlay2/nf74fpgi2h4w1tao8aiu5qr87/diff:/var/lib/docker/overlay2/2a2c68a919da7f157fe9cee745910175bc06b65b7d4d0bc8fe2aed397c4046da/diff:/var/lib/docker/overlay2/8582d3d6fcd83ab577d7e95528b0d14172d1d92bb7a16d05f3006ac5b696a068/diff:/var/lib/docker/overlay2/dc73a88715f77fa1b7cb36011ab7644e8b216d5e51f7d5a255982ee3ddc69403/diff:/var/lib/docker/overlay2/4411d30f0dc9056e3994938785b4b753b9e5dedba46b49649142e9cd86acabd0/diff:/var/lib/docker/overlay2/ef38bbab846be9a3b04ba6b9748d828d3df5c9fbdb6349e3d606d0c54dcf02ac/diff",
      "MergedDir": "/var/lib/docker/overlay2/8b5bf15317a6bf2f1d24a90d9f92be8ab7b0c0ab7d12bf9fc928ec48a8b426bb/merged",
      "UpperDir": "/var/lib/docker/overlay2/8b5bf15317a6bf2f1d24a90d9f92be8ab7b0c0ab7d12bf9fc928ec48a8b426bb/diff",
      "WorkDir": "/var/lib/docker/overlay2/8b5bf15317a6bf2f1d24a90d9f92be8ab7b0c0ab7d12bf9fc928ec48a8b426bb/work"
    },
    "Name": "overlay2"
  },
  "Mounts": [
    {
      "Type": "bind",
      "Source": "C:\\Users\\ilche\\AppData\\Roaming\\Microsoft\\UserSecrets",
      "Destination": "/root/.microsoft/usersecrets",
      "Mode": "ro",
      "RW": false,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "C:\\Users\\ilche\\AppData\\Roaming\\ASP.NET\\Https",
      "Destination": "/root/.aspnet/https",
      "Mode": "ro",
      "RW": false,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "C:\\Users\\ilche\\source\\repos\\WebApplication4",
      "Destination": "/app",
      "Mode": "",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/run/desktop/mnt/host/c/Users/ilche/source/repos/WebApplication4",
      "Destination": "/src",
      "Mode": "",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "C:\\Users\\ilche\\.nuget\\packages\\",
      "Destination": "/root/.nuget/fallbackpackages2",
      "Mode": "",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\NuGetPackages",
      "Destination": "/root/.nuget/fallbackpackages",
      "Mode": "",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "C:\\Users\\ilche\\vsdbg\\vs2017u5",
      "Destination": "/remote_debugger",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    }
  ],
  "Config": {
    "Hostname": "6eeb0ef14e49",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
      "443/tcp": {},
      "80/tcp": {}
    },
    "Tty": true,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [
      "NUGET_PACKAGES=/root/.nuget/fallbackpackages2",
      "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2",
      "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true",
      "ASPNETCORE_ENVIRONMENT=Development",
      "ASPNETCORE_URLS=https://+:443;http://+:80",
      "DOTNET_USE_POLLING_FILE_WATCHER=1",
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "DOTNET_RUNNING_IN_CONTAINER=true",
      "DOTNET_VERSION=6.0.15",
      "ASPNET_VERSION=6.0.15"
    ],
    "Cmd": [
      "-f",
      "/dev/null"
    ],
    "Image": "webapplication4:dev",
    "Volumes": null,
    "WorkingDir": "/app",
    "Entrypoint": [
      "tail"
    ],
    "OnBuild": null,
    "Labels": {
      "com.microsoft.created-by": "visual-studio",
      "com.microsoft.visual-studio.project-name": "WebApplication4"
    }
  },
  "NetworkSettings": {
    "Bridge": "",
    "SandboxID": "3109a3fd7f28de7f27051d2146660f30911b9532a86536889b8cd19f6107f511",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {
      "443/tcp": [
        {
          "HostIp": "0.0.0.0",
          "HostPort": "32786"
        }
      ],
      "80/tcp": [
        {
          "HostIp": "0.0.0.0",
          "HostPort": "32787"
        }
      ]
    },
    "SandboxKey": "/var/run/docker/netns/3109a3fd7f28",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "f9a6715f953ab00687c8a3ba82480fae69c3700bd3085211ddf82919be99931e",
    "Gateway": "172.17.0.1",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "172.17.0.3",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "MacAddress": "02:42:ac:11:00:03",
    "Networks": {
      "bridge": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": null,
        "NetworkID": "a997033547229e8f006d6349c480a952dfde1ae078d8a125e24d72a0dc14f953",
        "EndpointID": "f9a6715f953ab00687c8a3ba82480fae69c3700bd3085211ddf82919be99931e",
        "Gateway": "172.17.0.1",
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:03",
        "DriverOpts": null
      }
    }
  }
}
```

**Comment by sam-thibault** [comment]
Can you verify nothing else on the host is already running on 443?

**Comment by akerouanton** [comment]
@ilchenkoevgeny Can you run this command: `netstat -p TCP -onba | findstr LISTENING` in an administrator terminal and paste the result here please?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
