### ISSUE TITLE
docker volume update panics with no volume

### ISSUE THREAD

**Issue by anacrolix** [docker/cli#5418]
### Description

```
> docker volume update
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/docker/cli/cli/command/volume.newUpdateCommand.func1(0x0?, {0x1024207e0, 0x0, 0x0?})
	/go/src/github.com/docker/cli/cli/command/volume/update.go:23 +0xa0
main.runDocker.(*DockerCli).InstrumentCobraCommands.func4.2(0x14000710900?, {0x1024207e0, 0x0, 0x0})
	/go/src/github.com/docker/cli/cli/command/telemetry_utils.go:57 +0x68
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x14000710900, {0x140003ab670, 0x0, 0x0})
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:985 +0x840
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x140003a2000)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1041
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1034
main.runDocker({0x101b3a858?, 0x14000128c00}, 0x14000396000)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:414 +0x774
main.dockerMain()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:50 +0x1d0
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:32 +0x1c
```

### Reproduce

```
> docker volume update
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/docker/cli/cli/command/volume.newUpdateCommand.func1(0x0?, {0x1024207e0, 0x0, 0x0?})
	/go/src/github.com/docker/cli/cli/command/volume/update.go:23 +0xa0
main.runDocker.(*DockerCli).InstrumentCobraCommands.func4.2(0x14000710900?, {0x1024207e0, 0x0, 0x0})
	/go/src/github.com/docker/cli/cli/command/telemetry_utils.go:57 +0x68
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x14000710900, {0x140003ab670, 0x0, 0x0})
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:985 +0x840
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x140003a2000)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1041
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:1034
main.runDocker({0x101b3a858?, 0x14000128c00}, 0x14000396000)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:414 +0x774
main.dockerMain()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:50 +0x1d0
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:32 +0x1c
```

### Expected behavior

```
> docker volume update
"docker volume update" requires at least 1 argument.
```

### docker version

```bash
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.0 (165256)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /Users/anacrolix/.docker/cli-plugins/docker-scout

Server:
 Containers: 29
  Running: 0
  Paused: 0
  Stopped: 29
 Images: 4
 Server Version: 27.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: 1f16694d-253b-486c-84f6-919c47c90a10
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/anacrolix/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by laurazard** [comment]
Thanks for the report @anacrolix.

I can confirm/reproduce, so I'll take a look.
